### ISSUE TITLE
[Não consigo adicionar imagem]

### ISSUE THREAD

**Issue by Riwne** [Raul-rx7/Template_Relatorio_Estagio_UECE_FAFIDAM#1]
Olá, ME AJUDA! 
Não estou conseguindo adicionar imagens no escopo do texto em nenhuma parte do documeno.

**Comment by Raul-rx7** [comment]
Você pode ver em DICAS no seguinte link. 
https://github.com/Raul-rx7/Template_Relatorio_Estagio_UECE_FAFIDAM

**Comment by Riwne** [comment]
Ok, thanks <3
